import { FilterUIDefinition } from "./types";

export const STATIC_USER_VIEW_DEFINITIONS: FilterUIDefinition[] = [
  {
    id: "user_user_id",
    labelKey: "fields.userId",
    type: "string",
    operators: ["eq", "neq", "like", "ilike", "contains", "not-contains"],
    table: "users_view",
    subType: "user",
  },
  {
    id: "user_active_for",
    labelKey: "fields.activeForDays",
    type: "number",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "users_view",
    subType: "user",
  },
  {
    id: "user_first_active",
    labelKey: "fields.firstActive",
    type: "datetime",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "users_view",
    subType: "user",
  },
  {
    id: "user_last_active",
    labelKey: "fields.lastActive",
    type: "datetime",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "users_view",
    subType: "user",
  },
  {
    id: "user_total_requests",
    labelKey: "fields.totalRequests",
    type: "number",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "users_view",
    subType: "user",
  },
  {
    id: "user_average_requests_per_day_active",
    labelKey: "fields.avgRequestsPerDay",
    type: "number",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "users_view",
    subType: "user",
  },
  {
    id: "user_average_tokens_per_request",
    labelKey: "fields.avgTokensPerRequest",
    type: "number",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "users_view",
    subType: "user",
  },
  {
    id: "user_total_completion_tokens",
    labelKey: "fields.totalCompletionTokens",
    type: "number",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "users_view",
    subType: "user",
  },
  {
    id: "user_total_prompt_tokens",
    labelKey: "fields.totalPromptTokens",
    type: "number",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "users_view",
    subType: "user",
  },
  {
    id: "user_cost",
    labelKey: "fields.totalCost",
    type: "number",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "users_view",
    subType: "user",
  },
];

export const STATIC_SESSIONS_VIEW_DEFINITIONS: FilterUIDefinition[] = [
  {
    id: "session_session_id",
    labelKey: "fields.sessionId",
    type: "string",
    operators: ["eq", "neq", "like", "ilike", "contains", "not-contains"],
    table: "sessions_request_response_rmt",
    subType: "sessions",
  },
  {
    id: "session_session_name",
    labelKey: "fields.sessionName",
    type: "string",
    operators: ["eq", "neq", "like", "ilike", "contains", "not-contains"],
    table: "sessions_request_response_rmt",
    subType: "sessions",
  },
  {
    id: "session_created_at",
    labelKey: "fields.createdAt",
    type: "datetime",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "sessions_request_response_rmt",
    subType: "sessions",
  },
  {
    id: "session_latest_request_created_at",
    labelKey: "fields.latestRequestCreatedAt",
    type: "datetime",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "sessions_request_response_rmt",
    subType: "sessions",
  },
  {
    id: "session_total_tokens",
    labelKey: "fields.totalTokens",
    type: "number",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "sessions_request_response_rmt",
    subType: "sessions",
  },
  {
    id: "session_total_requests",
    labelKey: "fields.totalRequests",
    type: "number",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "sessions_request_response_rmt",
    subType: "sessions",
  },
  {
    id: "session_total_completion_tokens",
    labelKey: "fields.totalCompletionTokens",
    type: "number",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "sessions_request_response_rmt",
    subType: "sessions",
  },
  {
    id: "session_prompt_tokens",
    labelKey: "fields.totalPromptTokens",
    type: "number",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "sessions_request_response_rmt",
    subType: "sessions",
  },
  {
    id: "session_total_cost",
    labelKey: "fields.totalCost",
    type: "number",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "sessions_request_response_rmt",
    subType: "sessions",
  },
  {
    id: "session_tag",
    labelKey: "fields.tags",
    type: "string",
    operators: ["eq", "neq", "like", "ilike", "contains", "not-contains"],
    table: "sessions_request_response_rmt",
    subType: "sessions",
  },
];

export const STATIC_FILTER_DEFINITIONS: FilterUIDefinition[] = [
  {
    id: "response_id",
    labelKey: "fields.responseId",
    type: "string",
    operators: ["eq", "neq", "like", "ilike", "contains", "not-contains"],
    table: "request_response_rmt",
  },
  {
    id: "request_id",
    labelKey: "fields.requestId",
    type: "string",
    operators: ["eq", "neq", "like", "ilike", "contains", "not-contains"],
    table: "request_response_rmt",
  },
  {
    id: "user_id",
    labelKey: "fields.userId",
    type: "string",
    operators: ["eq", "neq", "like", "ilike", "contains", "not-contains"],
    table: "request_response_rmt",
  },
  {
    id: "organization_id",
    labelKey: "fields.organizationId",
    type: "string",
    operators: ["eq", "neq", "like", "ilike", "contains", "not-contains"],
    table: "request_response_rmt",
  },
  {
    id: "target_url",
    labelKey: "fields.targetUrl",
    type: "string",
    operators: ["eq", "neq", "like", "ilike", "contains", "not-contains"],
    table: "request_response_rmt",
  },
  {
    id: "request_body",
    labelKey: "fields.requestBody",
    type: "string",
    operators: ["contains", "not-contains", "like", "ilike"],
    table: "request_response_rmt",
  },
  {
    id: "response_body",
    labelKey: "fields.responseBody",
    type: "string",
    operators: ["contains", "not-contains", "like", "ilike"],
    table: "request_response_rmt",
  },
  {
    id: "country_code",
    labelKey: "fields.countryCode",
    type: "string",
    operators: ["eq", "neq", "like", "ilike", "contains", "not-contains"],
    table: "request_response_rmt",
  },
  {
    id: "prompt_id",
    labelKey: "fields.promptId",
    type: "string",
    operators: ["eq", "neq", "like", "ilike", "contains", "not-contains"],
    table: "request_response_rmt",
  },
  {
    id: "prompt_version",
    labelKey: "fields.promptVersion",
    type: "string",
    operators: ["eq", "neq", "like", "ilike", "contains", "not-contains"],
    table: "request_response_rmt",
  },
  {
    id: "provider",
    labelKey: "fields.provider",
    type: "string",
    operators: ["eq", "neq", "like", "ilike", "contains", "not-contains"],
    table: "request_response_rmt",
  },
  {
    id: "status",
    labelKey: "fields.statusCode",
    type: "number",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    valueOptions: [
      { labelKey: "values.status200", value: 200 },
      { labelKey: "values.status201", value: 201 },
      { labelKey: "values.status400", value: 400 },
      { labelKey: "values.status401", value: 401 },
      { labelKey: "values.status404", value: 404 },
      { labelKey: "values.status500", value: 500 },
    ],
    table: "request_response_rmt",
  },
  {
    id: "latency",
    labelKey: "fields.latency",
    type: "number",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "request_response_rmt",
  },
  {
    id: "cost",
    labelKey: "fields.cost",
    type: "number",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "request_response_rmt",
  },
  {
    id: "completion_tokens",
    labelKey: "fields.completionTokens",
    type: "number",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "request_response_rmt",
  },
  {
    id: "prompt_tokens",
    labelKey: "fields.promptTokens",
    type: "number",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "request_response_rmt",
  },
  {
    id: "prompt_cache_write_tokens",
    labelKey: "fields.promptCacheWriteTokens",
    type: "number",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "request_response_rmt",
  },
  {
    id: "prompt_cache_read_tokens",
    labelKey: "fields.promptCacheReadTokens",
    type: "number",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "request_response_rmt",
  },
  {
    id: "reasoning_tokens",
    labelKey: "fields.reasoningTokens",
    type: "number",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "request_response_rmt",
  },
  {
    id: "time_to_first_token",
    labelKey: "fields.timeToFirstToken",
    type: "number",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "request_response_rmt",
  },
  {
    id: "threat",
    labelKey: "fields.threat",
    type: "boolean",
    operators: ["is"],
    valueOptions: [
      { labelKey: "values.yes", value: true },
      { labelKey: "values.no", value: false },
    ],
    table: "request_response_rmt",
  },
  {
    id: "cache_enabled",
    labelKey: "fields.cacheEnabled",
    type: "boolean",
    operators: ["is"],
    valueOptions: [
      { labelKey: "values.yes", value: true },
      { labelKey: "values.no", value: false },
    ],
    table: "request_response_rmt",
  },
  {
    id: "cached",
    labelKey: "fields.cached",
    type: "boolean",
    operators: ["is"],
    valueOptions: [
      { labelKey: "values.yes", value: true },
      { labelKey: "values.no", value: false },
    ],
    table: "request_response_rmt",
  },
  {
    id: "helicone-score-feedback",
    labelKey: "fields.feedback",
    type: "boolean",
    operators: ["eq"],
    valueOptions: [
      { labelKey: "values.positive", value: true },
      { labelKey: "values.negative", value: false },
    ],
    table: "request_response_rmt",
  },
  {
    id: "ai_gateway",
    labelKey: "fields.aiGateway",
    type: "boolean",
    operators: ["is"],
    valueOptions: [
      { labelKey: "values.yes", value: true },
      { labelKey: "values.no", value: false },
    ],
    table: "request_response_rmt",
  },
  {
    id: "response_created_at",
    labelKey: "fields.responseCreatedAt",
    type: "datetime",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "request_response_rmt",
  },
  {
    id: "request_created_at",
    labelKey: "fields.requestCreatedAt",
    type: "datetime",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "request_response_rmt",
  },
  {
    id: "updated_at",
    labelKey: "fields.updatedAt",
    type: "datetime",
    operators: ["eq", "neq", "gt", "gte", "lt", "lte"],
    table: "request_response_rmt",
  },
  {
    id: "assets",
    labelKey: "fields.assets",
    type: "string",
    operators: ["contains", "in"],
    table: "request_response_rmt",
  },
];
